# -*- coding: utf-8 -*-
"""BMI Calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jCRVWqi6MPsKgh_b03YKpwbnM6i3OAky

**BMI Calculators**
"""

name = input("input your name: ")
weight = float (input("Input your weight in kilogram: "))
height = float (input("input your height in centimeter: "))
BMI = (weight * 10000) / (height * height)
print (BMI)

if BMI > 0:
  if(BMI <15):
    print(name, "You are Dangerous, Too Thin")
  elif(BMI <16):
    print(name, "You are Very Thin")
  elif(BMI <18.5):
    print(name, "You are Thin")
  elif(BMI <25):
    print(name, "You are Normal (Ideal Weight)")
  elif(BMI <30):
    print(name, "You are Fat")
  elif(BMI <35):
    print(name, "You are Class I obesity")
  elif(BMI <40):
    print(name, "You are Class II obesity")
  else:
    print(name, "you are Class III obesity")
else:
  print("Enter valid input !")

